# BEFORE YOU START:
#  docker pull selenoid/vnc:chrome_121.0
#  docker pull selenoid/video-recorder:latest-release

#  docker network ls
#  docker network create selenoid
#  docker network inspect [net_id]
#  docker ps
#  docker network connect selenoid [containers]
#  docker-compose up
networks:
  selenoid:
    external: true

services:
  selenoid:
    hostname: "selenoid"
    image: aerokube/selenoid:latest-release
    networks:
      - selenoid
    volumes:
      - "./browsers.json:/etc/selenoid/browsers.json:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./video:/opt/selenoid/video"
      - "./logs:/opt/selenoid/logs"
    command: [
      "-conf", "/etc/selenoid/browsers.json",
      "-video-output-dir", "/opt/selenoid/video",
      "-log-output-dir", "/opt/selenoid/logs",
      "-container-network", "selenoid"
    ]
    ports:
      - "4444:4444"

  selenoid-ui:
    image: aerokube/selenoid-ui
    hostname: selenoid-ui
    networks:
      - selenoid
    depends_on:
      - selenoid
    ports:
      - "8081:8080"
    command: [ "--selenoid-uri", "http://selenoid:4444" ]
